base/baseInit.sh
baseUnstable/baseInit.sh

https://github.com/Shippable/buildami/issues/32

added install ntp script

---

exec/execPack.sh

Use tee to get streaming output

---

base/basePack.sh
basePatch/basePatchPack.sh
baseUnstable/basePack.sh

Update remaining packer commands to use tee

---

base/basePack.sh
basePatch/basePatchPack.sh
baseUnstable/basePack.sh
exec/execPack.sh

Set pipefail so we know if the packer command failed

---

base/basePull.sh

Add drydock cpp images

---

exec/execPull.sh

genexec instead of runSh

---

base/baseInit.sh
baseUnstable/baseInit.sh

- https://github.com/Shippable/pm/issues/7761

adding google dns servers to docker options for stable and unstable amis

---

exec/execPull.sh

Fixes https://github.com/Shippable/buildami/issues/50

Removes mexec while building the ami

---

base/baseInit.sh

https://github.com/Shippable/buildami/issues/129

use static docker binaries

---

exec/execPull.sh

https://github.com/Shippable/buildami/issues/138

 pull u14cppall:prod

---

exec/execAMITmp.json
exec/patchDockerOptsTmp.sh

I have tested the script and it works okay. I haven't tested the packer build.
https://github.com/Shippable/buildami/issues/140

Update docker opts for tmp ami jobs

---

exec/execPull.sh

Clone cexec in tmp job

---

base/baseAMI.json
base/baseInit.sh
base/basePack.sh
basePatch/basePatchPull.sh
exec/execPull.sh

144 update ami scripts

---

base/baseAMI.json
base/baseInit.sh

executing init script as root

---

basePatch/basePatchPull.sh

fixing error command

---

base/baseInit.sh

adding tmp clone location

---

exec/execPull.sh

fixing perms for creating directory

---

base/baseInit.sh
exec/execAMITmp.json
exec/execPackTmp.sh
exec/execPull.sh

setting correct evs for stable ami

---

exec/execPull.sh

updating undefined variables

---

exec/execPull.sh

removing incorrect directives

---

exec/execPull.sh

fixing more typos

---

exec/execPackTmp.sh

https://github.com/Shippable/buildami/issues/144

fixing script for unstable ami

---

exec/execPackTmp.sh

fixing AMI type name

---

base/baseInit.sh
exec/execPull.sh

setting default value of subscription id

---

exec/execAMI.json
exec/execPack.sh

updating final release job to set correct envs

---

exec/execPack.sh

https://github.com/Shippable/buildami/issues/167

Sets SHIPPABLE_NODE_INIT_SCRIPT from the buildami_params

---

base/basePack.sh
exec/execPackTmp.sh

https://github.com/Shippable/buildami/issues/167

Updates files to pick the location of script from PARAMS

---

basePatch/basePatchAMI.json
basePatch/patchNameServer.sh

https://github.com/Shippable/buildami/issues/170

Updates files to patch rc base ami with correct nameserver

---

admiral/admiralAMI.json
admiral/admiralPack.sh

adding placeholder for building admiral ami

---

admiral/admiralPack.sh

fixing keys

---

admiral/admiralPack.sh

removing security group

---

admiral/admiralPack.sh

adding deploy keys

---

admiral/admiralAMI.json
admiral/admiralInit.sh
admiral/admiralPack.sh

hooking up ami builder function

---

admiral/admiralPack.sh

printing packer version

---

admiral/admiralAMI.json
admiral/admiralPack.sh

using correct credentials

---

admiral/admiralAMI.json

updating image name

---

admiral/admiralAMI.json
admiral/admiralInit.sh
admiral/admiralPack.sh

fixing version numbers

---

admiral/admiralAMI.json
admiral/admiralPack.sh

fixing script errors

---

admiral/admiralPack.sh

hooking up ami build job

---

admiral/admiralAMI.json

updating version number format

---

admiral/admiralAMI.json

making rc name unique

---

admiral/admiralInit.sh

removing authorized keys from root and ubuntu users

---

admiral/admiralInit.sh

removing password for shippable user

---

admiralPatch/admiralPatch.sh
admiralPatch/admiralPatchAMI.json
admiralPatch/admiralPatchPack.sh

adding patch job

---

README.md

commit to trigger sync

---

admiralPatch/admiralPatch.sh
admiralPatch/admiralPatchPack.sh

hooking up ami creation

---

admiralPatch/admiralPatchPack.sh

fixing packer json file path

---

admiral/admiralPack.sh
admiralPatch/admiralPatchPack.sh

fixing name for ami

---

admiralPatch/admiralPatch.sh
admiralPatch/admiralPatchAMI.json

stopping upstart job

---

admiralPatch/admiralPatch.sh

removing runtime and config dirs

---

admiralPatch/admiralPatch.sh

checking out release version

---

admiralPatch/admiralPatchAMI.json

fixing ami name

---

exec/execPull.sh

https://github.com/Shippable/buildami/issues/217

Updates files to pull genexec from drydock instead of shipimg

---

exec/execPull.sh

- https://github.com/Shippable/pm/issues/8670

updating ci image for zephyr

---

base/baseInit.sh

https://github.com/Shippable/buildami/issues/220

defaults SHIPPABLE_NODE_ARCHITECTURE & IS_SWAP_ENABLED

---

exec/execPull.sh

removing the old ones and moving to v0.1

updating zephyr tag to v0.1

---

admiral/admiralPack.sh
admiralPatch/admiralPatchPack.sh
base/basePack.sh
basePatch/basePatchPack.sh
exec/execPack.sh
exec/execPackTmp.sh

https://github.com/Shippable/beta/issues/710

Use the new aws v2 integration

---

admiral/admiralInit.sh

- https://github.com/Shippable/pm/issues/9125

upgrading kernel

---

base/baseInit.sh
base/basePull.sh

https://github.com/Shippable/buildami/issues/226

use new docker script to build baseami

---

base/baseInit.sh

https://github.com/Shippable/buildami/issues/226

extract node scripts from tarball instead of using git

---

base/basePull.sh

https://github.com/Shippable/buildami/issues/226

buildami, pull docker images

---

basePatch/basePatchPull.sh

update patch ami job to get latest reqproc and reqkick

---

base/baseAMI.json
base/baseInit.sh

build baseami, set IS_SWAP_ENABLED

---

basePatch/basePatchPull.sh

use sudo on base patch job for new components

---

basePatch/basePatchPull.sh

move NODE_SCRIPTS_LOCATION to /root/node

---

basePatch/basePatchPull.sh

patchBase - always remove existing NODE dir

---

exec/execPull.sh

https://github.com/Shippable/buildami/issues/231

update execPull job to setup grisham components on final ami

---

exec/execPull.sh

https://github.com/Shippable/buildami/issues/231

fix reqKick dir and update REL_VER for testing

---

exec/execPull.sh

https://github.com/Shippable/buildami/issues/231
https://github.com/Shippable/buildami/issues/232

adds sudo for npm install

---

exec/execAMI.json

https://github.com/Shippable/buildami/issues/268

run execPull.sh for final AMI building as root

---

shippable.yml

https://github.com/Shippable/buildami/issues/268

remove genexec_tag_push dependency for finalami for testing

---

base/baseInit.sh

https://github.com/Shippable/buildami/issues/289

adds dns settings to baseami

---

shippable.yml

https://github.com/Shippable/pm/issues/9972

update ami id for v614 patch job

---

base/baseInit.sh

https://github.com/Shippable/buildami/issues/299

adds REQKICK_DOWNLOAD_URL && CEXEC_DOWNLOAD_URL

---

shippable.yml
windowsBase/bootstrap_win.txt
windowsBase/sample_script.ps1
windowsBase/windowsBaseAMI.json
windowsBase/windowsBasePack.sh

https://github.com/Shippable/buildami/issues/301

adds sample windows ami job

---

shippable.yml
windowsBase/windowsBasePack.sh

https://github.com/Shippable/buildami/issues/301

Fix validation errors

---

windowsBase/windowsBaseAMI.json

#301 
Fixes the template error

removes unwanted comma in windowsBase

---

shippable.yml
windowsBase/windowsBaseAMI.json
windowsBase/windowsBasePack.sh

https://github.com/Shippable/buildami/issues/307

updates windows ami details

---

windowsBase/sample_script.ps1
windowsBase/windowsBaseAMI.json
windowsBase/windowsBaseInit.ps1
windowsBase/windowsBasePull.ps1

https://github.com/Shippable/buildami/issues/308
https://github.com/Shippable/buildami/issues/309

adds skeleton for windowsBaseInit and windowsBasePull

---

base/baseInit.sh
basePatch/basePatchPull.sh
exec/execPull.sh
shippable.yml

https://github.com/Shippable/buildami/issues/312

Update AMI build to fetch reports from S3

---

basePatch/basePatchPull.sh

Oops, didn't mean to remove /bin
https://github.com/Shippable/buildami/issues/312

Fix incorrect env

---

basePatch/basePatchPull.sh

https://github.com/Shippable/buildami/issues/312

And, more sudo

---

windowsBase/images.txt
windowsBase/windowsBaseAMI.json
windowsBase/windowsBaseInit.ps1
windowsBase/windowsBasePack.sh
windowsBase/windowsBasePull.ps1

https://github.com/Shippable/buildami/issues/308

Completes windowsBaseInit.ps1 and pulls all windows docker images

---

u16Base/baseInit.sh

Adds REPORTS_DOWNLOAD_URL to match Ubuntu 14.04.

---

shippable.yml

#321 
The "final" AMI will still be 14.04.

Sets final AMI back to Ubuntu 14.04.

---

u16Base/baseAMI.json
u16BasePatch/basePatchAMI.json
u16Exec/execAMI.json

Adds u16 to Ubuntu 16.04 AMI names.

---

shippable.yml

traditional AMIs build from u14 repqroc

---

exec/execPull.sh

https://github.com/Shippable/buildami/issues/342

Pull the default runSh microbase image

---

shippable.yml

#344
and remove u14 images from the u16 ami

add final job for u16

---

u16Base/images.txt

remove u14 images from u16 ami

---

c7BasePatch/basePatchAMI.json
c7BasePatch/basePatchPull.sh
c7Exec/execAMI.json
c7Exec/execPack.sh
c7Exec/execPull.sh
shippable.yml

add patch and final c7 jobs

---

c7BasePatch/basePatchPack.sh

add missing file

---

c7BasePatch/basePatchPull.sh
c7Exec/execPull.sh

c7 needs to explicitly add /usr/local/bin to path

---

c7BasePatch/basePatchPull.sh
c7Exec/execPull.sh

#349
verified this on a DO machine.

move path to npm command

---

c7BasePatch/basePatchPull.sh
c7Exec/execPull.sh

#349
verified on a centos machine running the same base prep ami

use full path of npm

---

shippable.yml

fix pipeline job script

---

windowsBase/basePack.sh
windowsBasePatch/basePatchPack.sh

correct the patch shell script

---

windowsBasePatch/basePatchPull.ps1

#339
noticed an error in the patch job (despite it not failing).  updating the script

remove bad syntax for ps1

---

exec/execAMIUpdate.json
exec/execPackUpdate.sh
shippable.yml

adding the tmp files back, and renaming to 'update' since they are only used in AMI update jobs.

add back tmp, rename to update

---

exec/execPackUpdate.sh

sh needs to call the correct json file

use correct json

---

exec/execPackUpdate.sh

remove last reference to tmp file

another tmp reference

---

u16Exec/execPull.sh

u16 doesnt need u14cpp, and genexec is not needed for grisham

remove unnecessary images

---

shippable.yml
windowsExec/execPull.ps1

u16Exec instead of exec, and remove kerneldown from windows

fix bad script

---

exec/execAMIUpdate.json
exec/execPackUpdate.sh
exec/execPull.sh
shippable.yml

https://github.com/Shippable/buildami/issues/383

Remove genExec, node.env from all u14 AMIs

---

c7Exec/execPull.sh
exec/execPull.sh
u16Exec/execPull.sh

Missed removing a few `update_envs`. Also, some artifacts of genexec remain from the base image. So, I'm removing them as well.
https://github.com/Shippable/buildami/issues/383
https://github.com/Shippable/buildami/issues/385
https://github.com/Shippable/buildami/issues/386
https://github.com/Shippable/buildami/issues/387

Remove existing genexec, related configs

---

windowsExec/execPull.ps1

#439
https://en.wikipedia.org/wiki/Eval#Windows_PowerShell

bash to powershell

---

windowsExec/execPull.ps1

use the ps1 script

---

windowsExec/execPull.ps1

#439 
trying to use env that is not in scope

fix bad env

---

windowsExec/execPull.ps1

check for empty string before splitting

---

windowsBasePatch/basePatchPull.ps1

https://github.com/Shippable/pm/issues/10749

 corrects node and reqkick script path for windows buildami patch

---

images/x86_64/CentOS_7/shippable.yml
images/x86_64/Ubuntu_14.04/shippable.yml
images/x86_64/Ubuntu_16.04/shippable.yml

completes #527 
ami-ids taken from current production 6.4.4 settings

add 644 update jobs

---

images/x86_64/Ubuntu_16.04/shippable.yml

fix spacing

---

gcp/templates/linux/imagesPull.sh

https://github.com/Shippable/buildami/issues/557

Remove or untag master images if not building master

---

c7BasePatch/basePatchPull.sh

adds /usr/local/bin to PATH similar to https://github.com/Shippable/buildami/pull/353/files

add /usr/local/bin to PATH

---

gcp/templates/linux/imagesPull.sh

https://github.com/Shippable/buildami/issues/557

Add missing sudo for CentOS

---

c7Exec/execPull.sh
exec/execPull.sh
u16Exec/execPull.sh
windowsExec/execPull.ps1

https://github.com/Shippable/heap/issues/2264

install node 8.11.2 in patch jobs

---

images/x86_64/WindowsServer_2016/shippable.yml

https://github.com/Shippable/heap/issues/2376

Push latest tag for Windows drydock images

---

images/x86_64/CentOS_7/shippable.yml
images/x86_64/Ubuntu_14.04/shippable.yml
images/x86_64/Ubuntu_16.04/shippable.yml

AMI IDs taken from current prod 6.5.4

add update jobs for aws 654 amis

---

images/aarch32/Ubuntu_16.04/shippable.yml

https://github.com/Shippable/buildami/issues/571
https://github.com/Shippable/buildami/issues/572

add jobs to build and tag aarch32_u16microbase img

---

gcp/templates/final_patch/downgradeKernel.sh
gcp/templates/final_patch/packer.json
images/x86_64/Ubuntu_14.04/shippable.yml

The Packer build will be tested in pipelines. The script to downgrade kernel works okay.
https://github.com/Shippable/buildami/issues/576

Add v582_u14_x8664_k313_gce_img job

---

gcp/templates/prep/packer.json

https://github.com/Shippable/buildami/issues/584

Remove extra comma in packer.json

---

images/x86_64/Ubuntu_14.04/shippable.yml

https://github.com/Shippable/buildami/issues/587

Split Docker 1.13 prep, patch jobs into jobs with different kernels

---

images/x86_64/CentOS_7/shippable.yml
images/x86_64/Ubuntu_14.04/shippable.yml
images/x86_64/Ubuntu_16.04/shippable.yml

Moving everything to templates to simplify modifying the files.

"Templatize" final build jobs

---

images/x86_64/CentOS_7/shippable.yml
images/x86_64/Ubuntu_14.04/shippable.yml
images/x86_64/Ubuntu_16.04/shippable.yml

Also, split up final task template to allow envs injection.
https://github.com/Shippable/pm/issues/11040

Add v6.6.4 GCE image jobs

---

images/x86_64/CentOS_7/shippable.yml
images/x86_64/Ubuntu_14.04/shippable.yml
images/x86_64/Ubuntu_16.04/shippable.yml

https://github.com/Shippable/pm/issues/11040

Build v6.6.4 on top of itself

---

images/x86_64/CentOS_7/shippable.yml
images/x86_64/Ubuntu_14.04/shippable.yml
images/x86_64/Ubuntu_16.04/shippable.yml

https://github.com/Shippable/pm/issues/11181

adds v6.7.4 gce SMI

---

images/x86_64/CentOS_7/shippable.yml
images/x86_64/Ubuntu_14.04/shippable.yml
images/x86_64/Ubuntu_16.04/shippable.yml
updateImages/production.csv
updateImages/rc.csv

add update jobs for 6.7.4 and add 674 to rc/prod ami checks

---

images/x86_64/Ubuntu_16.04/shippable.yml

fix alignment

---

images/x86_64/CentOS_7/shippable.yml
images/x86_64/Ubuntu_14.04/shippable.yml
images/x86_64/Ubuntu_16.04/shippable.yml

https://github.com/Shippable/pm/issues/11301

adds v684 gce jobs

---

images/x86_64/CentOS_7/shippable.yml

- https://github.com/Shippable/pm/issues/11301

fixing indentation for c7 ami job

---

updateImages/production.csv
updateImages/rc.csv

- https://github.com/Shippable/pm/issues/11301

updating rc and prod csv with v6.8.4 images

---

images/x86_64/CentOS_7/shippable.yml
images/x86_64/Ubuntu_14.04/shippable.yml
images/x86_64/Ubuntu_16.04/shippable.yml

https://github.com/Shippable/pm/issues/11411

adds v694 gce image building jobs

---

shippable.templates.yml

https://github.com/Shippable/pm/issues/11413

export SOURCE_IMAGE_FAMILY before building task

---

gcp/templates/prep/packer.json

- https://github.com/Shippable/heap/issues/2619

rebooting the host after upgrading kernel

---

images/x86_64/WindowsServer_2016/shippable.yml
windowsBase/images.txt
windowsBasePatch/images.txt
windowsExec/images.txt

https://github.com/Shippable/buildami/issues/628
https://github.com/Shippable/buildami/issues/629
https://github.com/Shippable/buildami/issues/630
https://github.com/Shippable/buildami/issues/631
https://github.com/Shippable/buildami/issues/632
https://github.com/Shippable/buildami/issues/633
https://github.com/Shippable/buildami/issues/634
https://github.com/Shippable/buildami/issues/635
https://github.com/Shippable/buildami/issues/636

Remove aspnetcore image in buildami 

---

images/x86_64/CentOS_7/shippable.yml
images/x86_64/Ubuntu_14.04/shippable.yml
images/x86_64/Ubuntu_16.04/shippable.yml

https://github.com/Shippable/pm/issues/11476
Probably we should make this an MVP as part of the drydock release heap

v6.10.4 gce jobs

---

updateImages/production.csv

remove bad amis to avoid null error

---

updateImages/production.csv

add 6.10.4 to csv list

---

gcp/x86_64/CentOS_7/final/codeRefresh.sh

https://github.com/Shippable/pm/issues/11542
removing the /data folder so that docker service restarts correctly

removing /data folder to fix the v694 C7 SMI

---

c7Base/images.txt
images/x86_64/CentOS_7/shippable.yml

https://github.com/Shippable/pm/issues/11554

adding c7golall pipeline

---

c7Base/images.txt
images/x86_64/CentOS_7/shippable.yml

https://github.com/Shippable/pm/issues/11555

Adding c7cloall Pipeline 

---

updateImages/production.csv

https://github.com/Shippable/pm/issues/11542

update only GCE images

---

c7Base/images.txt
images/x86_64/CentOS_7/shippable.yml

https://github.com/Shippable/pm/issues/11558

adding pipeline for c7scaall image 

---

c7Base/images.txt
images/x86_64/CentOS_7/shippable.yml

https://github.com/Shippable/pm/issues/11560

adding pipeline for c7 phpall image 

---

images/x86_64/CentOS_7/shippable.yml
images/x86_64/Ubuntu_14.04/shippable.yml
images/x86_64/Ubuntu_16.04/shippable.yml

https://github.com/Shippable/heap/issues/2662

renaming gcc v6.11.4 to v6.12.4

---

gcp/templates/prep/packer.json
gcp/x86_64/CentOS_7/prep/init.sh

add centos user to google-sudoers group

---

gcp/templates/prep/packer.json

remove comma

---

gcp/x86_64/CentOS_7/prep/init.sh

add centos to google-sudoers grp all the time

---

gcp/x86_64/CentOS_7/patch/codePull.sh

https://github.com/Shippable/buildami/pull/676

add ssh directory

---

gcp/x86_64/Ubuntu_14.04/final/additionalPackages.sh

#679
copied from u16, but package version changed based on the latest available for u14.04.
final `packer.json` is shared for all gcp, so no additional change is required.

add additionalpackages file for u14 final

---

gcp/x86_64/CentOS_7/prep/init.sh
gcp/x86_64/Ubuntu_14.04/prep/init.sh
gcp/x86_64/Ubuntu_16.04/prep/init.sh

#683
verified the scripts run as expected on each OS.

add rng-tools to prep for master ami

---

gcp/x86_64/CentOS_7/prep/init.sh

passwordless sudo command for centos

---

images/x86_64/CentOS_7/shippable.yml
images/x86_64/Ubuntu_14.04/shippable.yml
images/x86_64/Ubuntu_16.04/shippable.yml

https://github.com/Shippable/pm/issues/11714
https://github.com/Shippable/pm/issues/11715
https://github.com/Shippable/pm/issues/11716

Adding gce_img for v7.1.4  

---

images/x86_64/CentOS_7/shippable.yml
images/x86_64/Ubuntu_14.04/shippable.yml
images/x86_64/Ubuntu_16.04/shippable.yml
images/x86_64/WindowsServer_2016/shippable.yml

get new update jobs ready for new drydock release
https://github.com/Shippable/pm/issues/11721

add update jobs for aws AMIs 714 release

---

gcp/x86_64/Ubuntu_16.04/patch/codePull.sh

https://github.com/Shippable/pm/issues/11721

waiting for apt resource in patch jobs

---

images/x86_64/CentOS_7/shippable.yml

- https://github.com/Shippable/buildami/issues/697

triggering all language image tag jobs for C7 from drydock_release job

---

c7Exec/execPack.sh
images/x86_64/CentOS_7/shippable.yml

- https://github.com/Shippable/buildami/issues/697

creating C7 AMI only when shippable release == drydock release

---

c7Exec/execPack.sh

-https://github.com/Shippable/buildami/issues/697

temporary changes for testing ami creation

---

c7Exec/execPack.sh

- https://github.com/Shippable/buildami/issues/697

image pull tested successfully, reverting changes

---

images/x86_64/Ubuntu_14.04/shippable.yml

- https://github.com/Shippable/buildami/issues/699

triggering u14 image tag jobs from drydock_release

---

shippable.templates.yml

- https://github.com/Shippable/buildami/issues/699

temporary change to test image tagging

---

c7Exec/execPack.sh
exec/execPack.sh
images/x86_64/Ubuntu_14.04/shippable.yml
shippable.templates.yml

- https://github.com/Shippable/buildami/issues/699

creating u14 ami only when new drydock release is created

---

images/x86_64/Ubuntu_16.04/shippable.yml

- https://github.com/Shippable/buildami/issues/701

removing u16 language images dependency on prod_release

---

images/aarch64/Ubuntu_16.04/shippable.yml

- https://github.com/Shippable/buildami/issues/703

removing aarch64 u16 language images dependency on prod_release

---

images/x86_64/WindowsServer_2016/shippable.yml

- https://github.com/Shippable/buildami/issues/707

removing win2k16 language images dependency on prod_release

---

images/x86_64/WindowsServer_2016/shippable.yml

- https://github.com/Shippable/buildami/issues/707

skipping win2k16 ami creation if drydock release is not created

---

shippable.templates.yml

- https://github.com/Shippable/pm/issues/11513

temporarily commenting out code to test image tagging

---

shippable.templates.yml

- https://github.com/Shippable/pm/issues/11513

restoring commented code

---

images/x86_64/CentOS_7/shippable.yml
images/x86_64/Ubuntu_14.04/shippable.yml
images/x86_64/Ubuntu_16.04/shippable.yml

https://github.com/Shippable/pm/issues/11803
https://github.com/Shippable/pm/issues/11804
https://github.com/Shippable/pm/issues/11805

Adding gce_img for v7.2.4

---

images/x86_64/Distroless/shippable.yml

https://github.com/Shippable/buildami/issues/737
Script is similar to [how we windows build images](https://github.com/Shippable/buildami/blob/master/images/x86_64/WindowsServer_2016/shippable.yml#L60-L73).

Adds job for building drydock/distrobase:master
