Shippable/buildami

.gitignore, base/baseAMI.json
- adding sleep for 30 seconds to let OS boot correctly. this is mentioned in the first `note` in `packer` docs: https://www.packer.io/intro/getting-started/provision.html
=> giving some time for OS to initialize

basePatch/basePatchAMI.json, baseUnstable/baseAMI.json
- giving both stable and unstable ami some time to boot
=> adding sleep when building stable and unstable AMIs

exec/execAMI.json, exec/execAMITmp.json, exec/patchNameServer.sh
https://github.com/Shippable/buildami/issues/170
From AWS Documentation
```
To configure an EC2 instance running Ubuntu or Debian Linux to use static DNS server entries, use a text editor such as vim to edit the file /etc/dhcp/dhclient.conf and add the following line to the end of the file:
supersede domain-name-servers xxx.xxx.xxx.xxx, xxx.xxx.xxx.xxx;
Where xxx.xxx.xxx.xxx is the IP address of a DNS server that you want the EC2 instance to use.
```
https://aws.amazon.com/premiumsupport/knowledge-center/ec2-static-dns-ubuntu-debian/
=> Updates files to replace nameserver values to 8.8.8.8 and 8.8.4.4

base/baseAMI.json
RC buildami is failing  due to lack of space 
https://app.shippable.com/github/Shippable/jobs/build_baseami/builds/5a2e3bebb9ead1070038f249/console
increase block device size to fix the issue
=> increase block device size while building AMI

exec/execPull.sh
https://github.com/Shippable/buildami/issues/232 
this was added for testing as is no longer needed.
=> remove REL_VER = master for execPull job

shippable.yml
https://github.com/Shippable/buildami/issues/293
AMI id set according to latest AMI id for `finalami_prep` - 
https://app.shippable.com/github/Shippable/jobs/finalami_prep/dashboard
=> adds pipeline job to patch ami v6.1.4

shippable.yml
current AMI built by `finalami_prep` has pulled latest language images, 
now we need to pull build components tagged with - v6.1.4 for genexec and reproc 
so, we will have to update AMI id of v6.1.4 patch job before we run it. 
thus, the AMI built after this will have latest languages as well as v6.1.4 components. 
finalami_prep job - https://app.shippable.com/github/Shippable/jobs/finalami_prep/dashboard
=> update ami id for v614 patch job so that it can get latest languages

exec/execPack.sh
https://github.com/Shippable/pm/issues/9972
we are not pulling tagged drydock language images because the environment variable `IMAGE_NAMES_SPACED` is not getting set correctly in `finalami_prep` job.
this is because we are using `shipctl` to `get_resource_state` which returns <RES_NAME>_STATE variable while `version.json` is present in <RES_NAME>_PATH variable. 
last change was here - https://github.com/Shippable/buildami/commit/64bebee3476297349bcb6ac799c78c5e0d001ad6#diff-8248f06590528ff27b6eec72087896d4R28
=> fix  while building final ami

exec/execAMI.json
https://github.com/Shippable/pm/issues/9972
**we introduced a new environment variable which has spaces - $IMAGE_NAMES_SPACED**. as per packer docs, https://www.packer.io/docs/provisioners/shell.html#sudo-example
```
"echo 'packer' | sudo -S sh -c '{{ .Vars }} {{ .Path }}'"
```
The above example won't work if your environment vars contain spaces or single quotes; in these cases try removing the single quotes:
```
"echo 'packer' | sudo -S env {{ .Vars }} {{ .Path }}"
```
=> finalami_prep - fix for environment variables with spaces

shippable.yml, windowsBase/bootstrap_win.txt
https://github.com/Shippable/buildami/issues/301
shipctl replace uses `envsubst` internally ( https://github.com/Shippable/node/blob/8547cef4a40372ee402fb4f0435b3b56134d6e23/shipctl/x86_64/Ubuntu_16.04/shippable_replace#L15 )
`envsubst` does two things
- $some_var is an exported env, then substitute the respective value
- $some_var is not an exported env, then substitute with empty string.
This is causing the unexpected portions of `bootstrap_win.txt` to be replaced with empty string
```
<powershell>
$Key = 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System'
$Setting = 'LocalAccountTokenFilterPolicy'
</powershell>
```
becomes
```
<powershell>
= 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System'
= 'LocalAccountTokenFilterPolicy'
</powershell>
```
=> Uses sed instead of shipctl

shippable.yml, windowsBase/sample_script.ps1, windowsBase/windowsBaseAMI.json
https://github.com/Shippable/buildami/issues/301
Changing the `on_failure` block, because when a failure occurs, we seem to read a file that doesn't exist
This is happening for all the existing jobs in `buildami` like `baseami_prep` ( https://app.shippable.com/github/Shippable/jobs/baseami_prep/builds/5a7b118ea6e8350700e08ff0/console ). I guess this is happening due to wrong path being passed. So, changing it to explicitly go into the gitRepo directory using `shipctl` ( just like we do in task )
=> simplifies inline and sample scripts

windowsBase/windowsBasePack.sh
https://github.com/Shippable/buildami/issues/308
Currently the windows AMI packaging job fails 
https://app.shippable.com/github/Shippable/jobs/windowsbaseami_prep/builds/5a9e2aec5241fd1800de8b5e/console
```
1520316790,,ui,say,==> amazon-ebs: Provisioning with powershell script: ./windowsBasePull.ps1
1520316792,,ui,message,    amazon-ebs: #< CLIXML
1520316792,,ui,message,    amazon-ebs: RES_IMG_VER_NAME=
1520316792,,ui,message,    amazon-ebs: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> …
```
=> adds missing parts of windowsBasePack.sh

windowsBase/windowsBaseAMI.json
https://github.com/Shippable/buildami/issues/319
Followed https://www.packer.io/docs/builders/amazon-ebs.html#ami_groups for making the AMI public.
=> make windows AMI public

windowsBase/bootstrap_win.txt
https://github.com/Shippable/buildami/issues/326
Currently, user data that we send via ec2 is not being executed in our custom windows AMI. So, we need to execute
```
C:\ProgramData\Amazon\EC2-Windows\Launch\Scripts\InitializeInstance.ps1 –Schedule
```
to enable it to run on every boot.
Reference: https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/ec2launch.html#ec2launch-config
=> Execute User data for subsequent boots

windowsBase/bootstrap_win.txt, windowsBase/windowsBaseAMI.json
https://github.com/Shippable/buildami/issues/326
Windows AMI started failing from https://app.shippable.com/github/Shippable/jobs/windowsbaseami_prep/builds/5aa26dc6ec373f1700486137/console 
The only change done was an addition of a command to the user data script. Moving this script to packer config file, to see if the problem is because of it.
=> moves instance init to inline powershell

windowsBase/windowsBaseAMI.json
https://github.com/Shippable/buildami/issues/326
Seeing the following error in Windows AMI building.
```
#< CLIXML
1520831369,,ui,message,    amazon-ebs: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><S S="Error">At C:\Windows\Temp\script-5aa60361-146c-6ea9-f7ff-c6a00993f5c7.ps1:1 char:75_x000D__x000A_</S><S S="Error">+ ... \Amazon\EC2-Windows\Launch\Scripts\InitializeInstance.ps1 â€“Schedule_x000D__x000A_</S><S S="Error">+ …
```
=> replaces hyphen in windowsBaseAMI powershell command

c7Base/baseInit.sh
#337 
centos doesnt have wget by default. using curl instead.
=> update the baseinit ami job for c7

shippable.yml
#349 
c7 still uses a u16 reqproc, so there is no c7 version of the reqproc job.
=> correct the reqproc IN to c7 patch

shippable.yml
#439
got this from the admiral AMI tables, set for 6.3.4 windows in prod.
=> 634 update job should use current prod ami

gcp/templates/linux/imagesPull.sh
These two jobs failed -- https://app.shippable.com/github/Shippable/jobs/v644_c7_x8664_gce_img/builds/5b18cae357086e060094cf70/console, https://app.shippable.com/github/Shippable/jobs/v634_c7_x8664_gce_img/builds/5b18cad7e59fcc07008523ef/console
https://github.com/Shippable/buildami/issues/557
=> Skip image removal if there are no images to remove

images/x86_64/Ubuntu_16.04/shippable.yml
u16microbase doesn't build from u16, so it shouldn't list that as an IN.
=> fix u16microbase job

gcp/templates/prep/99-shippable.conf, gcp/templates/prep/copyConfigs.sh, gcp/templates/prep/packer.json
https://github.com/Shippable/buildami/issues/574
I haven't copied to file directly as it's unlikely to work without sudo. [From the docs](https://www.packer.io/docs/provisioners/file.html):
>The recommended usage of the file provisioner is to use it to upload files, and then use shell provisioner to move them to the proper place, set permissions, etc.
I have **not** tested the Packer script, I'll use the pipeline to see if this works. I have tested the config however and it works.
=> Add config to prevent IPv4 forwading getting disabled

images/x86_64/CentOS_7/shippable.yml, images/x86_64/Ubuntu_14.04/shippable.yml, images/x86_64/Ubuntu_16.04/shippable.yml
We rebuilt everything from the base image so that it gets the correct kernel versions and any other changes. Now, we can go back to using the built image to speed up final builds as before.
https://github.com/Shippable/buildami/issues/587
=> Build on top of previous image

images/x86_64/CentOS_7/shippable.yml, images/x86_64/Ubuntu_14.04/shippable.yml, images/x86_64/Ubuntu_16.04/shippable.yml
AMI-ids taken from latest runs of prod "finalami_prep" jobs for u14, u16, and c7.
windows AMIs are being manually created, so that update job is not present.
=> add update jobs for the aws amis v664

images/x86_64/Ubuntu_14.04/shippable.yml
https://github.com/Shippable/pm/issues/11136
we don't need to build u14microbase image on changes u14. These need to be built only on change to u14microbase repo
=> build microbase image only on change to microbase repo

updateImages/adapter.sh, updateImages/production.csv, updateImages/rc.csv, updateImages/shippable.yml, updateImages/update_images.sh
Notes:
1. I have not added Windows images as some of them are manual. The lists can be extended to add them or any other images.
1. By default, only "plan" will run. `PLAN_ONLY: false` needs to be passed explicitly to update the images.
=> Add jobs to update images

basePatch/basePatchPull.sh, c7BasePatch/basePatchPull.sh, c7Exec/execPull.sh, exec/execPull.sh, u16BasePatch/basePatchPull.sh, u16Exec/execPull.sh, windowsBasePatch/basePatchPull.ps1, windowsExec/execPull.ps1
#598 
Adds `--unsafe-perm=true --allow-root` to `npm install` to install `diskusage`.
=> #598; updates reqKick npm install.

shippable.templates.yml
Shippable/pm#11413
c7 x86-64 is hardcoded, but we can use OS and ARCHITECTURE instead
=> use os and arch in template

gcp/x86_64/CentOS_7/final/codeRefresh.sh
docker doesn't downgrade in centos. so we will have to remove it before re installing it. This is a one time thing. I will remove this code once the images get built.
https://github.com/Shippable/pm/issues/11542
=> remove docker before re installing it

gcp/templates/final/packer.json, gcp/x86_64/Ubuntu_16.04/final/additionalPackages.sh
#669
adds new script to install rng-tools for u16 gcp machines in the "final" ami jobs.
=> install rng-tools

gcp/templates/final/packer.json
#669 
background process was preventing apt-get from being able to obtain the lock, so i'm moving the script to the end of the flow, rather than adding sleep.
=> rearrange script order u16 gcp final

gcp/templates/patch/packer.json, gcp/x86_64/CentOS_7/patch/codePull.sh
This is a POC. We will create a new user `centos-debug` and all the required perms to it. The `ssh_username` user which is `centos` in our case, is getting its sudo perms getting stripped at the end of the packer build.
I will be merging this PR myself and revert this later after verification. I have spoken to @rageshkrishna about this.
=> add a new user centos-debug(will be reverted)

gcp/x86_64/CentOS_7/final/additionalPackages.sh
#681 
also makes the u14 script executable.  The packer script itself does a chmod, so making the script executable is not necessary, but I think it could potentially prevent confusion and errors later on.
=> add additionalpackages file for c7 final

gcp/x86_64/CentOS_7/final/additionalPackages.sh, gcp/x86_64/CentOS_7/prep/init.sh, gcp/x86_64/Ubuntu_14.04/final/additionalPackages.sh, gcp/x86_64/Ubuntu_14.04/prep/init.sh, gcp/x86_64/Ubuntu_16.04/final/additionalPackages.sh, gcp/x86_64/Ubuntu_16.04/prep/init.sh
#683 
seems that for u16, a lack of apt-get update is preventing the correct version of rng-tools from being recognized.  Moving the install to be after the node-init-script should ensure that an update occurs before the installation is attempted.  This also avoids having to add a second apt-get update command.
Though the other OS scripts don't currently run into the same error, I thought it would be best to keep them all consistent with each other.
=> remove references to specific versions

images/x86_64/CentOS_7/shippable.yml, images/x86_64/Ubuntu_14.04/shippable.yml, images/x86_64/Ubuntu_16.04/shippable.yml, updateImages/production.csv, updateImages/rc.csv
https://github.com/Shippable/pm/issues/11629
adds update jobs for the newest AMIs, also updates the CSVs so that the SMI update automation job can be used.
=> update for 6.12.4 release

images/x86_64/CentOS_7/shippable.yml, images/x86_64/Ubuntu_14.04/shippable.yml, images/x86_64/Ubuntu_16.04/shippable.yml, updateImages/production.csv, updateImages/rc.csv
https://github.com/Shippable/pm/issues/11721
AMIs for 714 update jobs were updated based on what was deployed to prod
=> enhance scripts for the new 714 amis

images/x86_64/CentOS_7/shippable.yml
- https://github.com/Shippable/buildami/issues/697
=> linking centos base image tagging with drydock release

images/x86_64/CentOS_7/shippable.yml
- https://github.com/Shippable/buildami/issues/698
=> removing centos base image dependency on prod_release

images/aarch32/Ubuntu_16.04/shippable.yml
- https://github.com/Shippable/buildami/issues/705
=> removing aarch32 u16 language images dependency on prod_release

images/x86_64/CentOS_7/shippable.yml, images/x86_64/Ubuntu_14.04/shippable.yml, images/x86_64/Ubuntu_16.04/shippable.yml, images/x86_64/WindowsServer_2016/shippable.yml, updateImages/production.csv, updateImages/rc.csv
https://github.com/Shippable/pm/issues/11831
- adds `update` jobs for aws 7.2.4 release to the pipeline
- adds 7.2.4 lines to the machine image auto-update script
- adds windows jobs to the machine image auto-update script
=> add update jobs for 7.2.4
